### ISSUE TITLE
Country parameter issue

### ISSUE THREAD

**Issue by Djeef** [naimo84/node-red-contrib-dyson-purelink#10]
Hi, I'm french so my Country-Code is FR but the node is not working at all...

I saw in the code that the third parameter (country) of the DysonPureLine object instantiation is a fixed value 'DE'

In dyson-link.ts 
`let pureLink = new DysonPurelink(node.config.username, node.config.password, 'DE');`

I'm not sure, but It should be something like 
`let pureLink = new DysonPurelink(node.config.username, node.config.password,  node.config.country);` 
no ?

**Comment by naimo84** [comment]
Hi Djeef, 

sorry for this, I fixed the issue and v0.1.4 is already on the way 😉 

Greets,
Benjamin
