### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by haydendonald** [naimo84/node-red-contrib-dyson-purelink#11]
Hi i've come across your project after recently getting a Dyson Heat+Cool and was wondering if it would be possible to add the heat functionality? It works perfectly but would be great if i could be able to set the temperature.

Thanks heaps if this is possible!

**Comment by naimo84** [comment]
Hi @haydendonald, 

sorry for the very late response. I've added the heat function with v0.1.5. It's already on the way.

Greets,
Benjamin
