### ISSUE TITLE
Some missing fan types

### ISSUE THREAD

**Issue by etc6849** [naimo84/node-red-contrib-dyson-purelink#12]
Great module.  Very much appreciated.

One of the my purifiers work, while the other doesn't.  I ended up removing it from my Dyson account for now, but it is a model HP02 (aka 455).

I found the additional product types below from here:
https://github.com/lukasroegner/homebridge-dyson-pure-cool/blob/master/src/dyson-pure-cool-device.js

   ` // Creates the device information from the API results
    let model = 'Pure Cool';
    let hardwareRevision = '';
    let hasHeating = false;
    let hasHumidifier = false;
    let hasJetFocus = false;
    let hasAdvancedAirQualitySensors = false;
    switch (productType) {
        case '358':
            model = 'Dyson Pure Humidify+Cool';
            hardwareRevision = 'PH01';
            hasAdvancedAirQualitySensors = true;
            hasHumidifier = true;
            hasJetFocus = true;
            break;
        case '438':
            model = 'Dyson Pure Cool Tower';
            hardwareRevision = 'TP04';
            hasJetFocus = true;
            hasAdvancedAirQualitySensors = true;
            break;
        case '455':
            model = 'Dyson Pure Hot+Cool Link';
            hardwareRevision = 'HP02';
            hasHeating = true;
            hasJetFocus = true;
            break;
        case '469':
            model = 'Dyson Pure Cool Link Desk';
            hardwareRevision = 'DP01';
            break;
        case '475':
            model = 'Dyson Pure Cool Link Tower';
            hardwareRevision = 'TP02';
            break;
        case '520':
            model = 'Dyson Pure Cool Desk';
            hardwareRevision = 'DP04';
            hasJetFocus = true;
            hasAdvancedAirQualitySensors = true;
            break;
        case '527':
            model = 'Dyson Pure Hot+Cool';
            hardwareRevision = 'HP04';
            hasJetFocus = true;
            hasAdvancedAirQualitySensors = true;
            hasHeating = true;
            break;
    }`

**Comment by naimo84** [comment]
Hi etc,

sorry for the late response. M family and I were on vacation, after the whole corona thing.
I'll have a look at the homebridge code and will report back.

regards,
Benjamin

**Comment by etc6849** [comment]
Thanks!  If it helps, I installed Home Assistant to test its Dyson functionality, and it does work:
https://www.home-assistant.io/integrations/dyson/

Hopefully you can add more models to your wonderful node!  I really have no plans to use Home Assistant on a permanent basis though as I have everything automated already on a different system.  My plan was to use node red to send TCP packets to my main HA system.  I've done this in the past with other node red flows, and it's been very handy.

**Comment by naimo84** [comment]
Hey, 

may you please try v0.2.0? I tried to add the additional device types. As I don't own this models, it's hard for me to test ;)

Greets,
Benjamin
