### ISSUE TITLE
TP02 fanspeed isn't working

### ISSUE THREAD

**Issue by etc6849** [naimo84/node-red-contrib-dyson-purelink#13]
I am able to turn my TP02 on and off by sending commands, but can't get fan speed to work.  No matter what value is passed, fan speed goes to 1.

![image](https://user-images.githubusercontent.com/2585352/82973696-18f02400-9fa6-11ea-89a3-8bce66e6e380.png)

**Comment by naimo84** [comment]
Hi @etc6849 ,

Have you tried the percent in percent? so 100 instead of 1?

msg.payload = {”action”: ”setFanSpeed“, ”speed”: 100}
msg.payload = {”action”: ”setFanSpeed“, ”speed”: 50}
...

Sorry, I have to write this down to README ;)

Greets,
Benjamin

**Comment by etc6849** [comment]
Yes, I have defined the object both ways.  The node-Red debugger outputs the debug message as shown regardless...

`flow.set('tcpsess', msg._session) || flow.get('tcpsess');
msg.payload = Buffer.from(msg.payload);
var sAction = msg.payload.toString();
sAction = sAction.trim();
var aCommand = sAction.split(",");
sAction = aCommand[0];
var oPayload = {};

switch(sAction) {
    case "setFanSpeed":
        var sSpeed = aCommand[1];
        oPayload = {"action":sAction,"speed":90};
        break;
    default:
        oPayload = {action:sAction};
}

msg.payload = oPayload;

return msg;`
