### ISSUE TITLE
Use in Node RED

### ISSUE THREAD

**Issue by ldiekmann** [naimo84/node-red-contrib-dyson-purelink#14]
Hi,

unfortunately no signals are sent to my Dyson and I don't get any values. Is there an example here that you can give me?

Thanks in advance.
Lars

**Comment by ldiekmann** [comment]
Hi,
I have now managed it myself.

**Comment by ldiekmann** [comment]
Good Morning,

unfortunately everything keeps hanging up with me. I get no values again or the Dyson is no longer controlled.
Can someone tell me what i'm making bottle I have to say that I am a newcomer to Node-Red. Enclosed pictures of my node.
Thanks in advance.

Greetings Lars

![Node](https://user-images.githubusercontent.com/67023005/85096819-b92c1800-b1f5-11ea-81a4-9ada25fa5711.png)
![Auto-Aus](https://user-images.githubusercontent.com/67023005/85096828-c34e1680-b1f5-11ea-9bc6-749886bf6cb3.png)
![dyson-link](https://user-images.githubusercontent.com/67023005/85096838-cc3ee800-b1f5-11ea-9365-474f19630a2b.png)
![Auto EIN](https://user-images.githubusercontent.com/67023005/85096849-d5c85000-b1f5-11ea-8c43-e782dea45bc0.png)
![An Dyson](https://user-images.githubusercontent.com/67023005/85096858-dd87f480-b1f5-11ea-8449-0c3e02a98e2a.png)

**Comment by Tylli** [comment]
Hey. Starting today all of a sudden I have the same problem. It worked between 11 and 15 o‘clock. Then there are no more messages from the dyson. I already reset the unit twice.

**Comment by ldiekmann** [comment]
Hi. Ich bin auch erst seit 2 Tagen dabei.
Das die Probleme von der Dyson Cloud kommen, habe ich auch vermutet. Komischerweise funktioniert trotzdem alles über die App.

**Comment by Tylli** [comment]
Schau mal ob es jetzt wieder geht, ich habe grade vor 2 Minuten wieder Nachrichten bekommen. Vielleicht gibt es eine maximale Anfragenzahl/Stunde

**Comment by ldiekmann** [comment]
Ganz kurz ging es. (Einmal)
Jetzt wieder nichts.
Kannst du bitte mal Scrennshots von deinem Flow schicken?

**Comment by Tylli** [comment]
![Uploading 85167905...]()

![Uploading 85167918...]()

**Comment by Tylli** [comment]
![Uploading 85167979...]()

**Comment by Tylli** [comment]
![Unbenannt](https://user-images.githubusercontent.com/67158524/85172233-e8cc3600-b270-11ea-9b29-b8eac1784be9.jpg)
![Unbenannt2](https://user-images.githubusercontent.com/67158524/85172240-ebc72680-b270-11ea-968b-89eae9a1ddf3.jpg)


Ich hole mir die Infos über ein Inject und konvertiere diese dann um, sodass ich die passenden Topics in Homebridge ansprechen kann. Seit einer Stunde etwa läuft es jetzt wieder. Die Infos werden alle 5 Minuten aktualisiert.

Was ich noch nicht hinbekommen habe ist einen Ein/Ausschalter zu integrieren. Aber ich habe mit Programmierung und co noch nie etwas am Hut gehabe und bin viel mit learning by doing unterwegs.

**Comment by ldiekmann** [comment]
Kannst du mir den Flow bitte als Export schicken, dann kann ich sehen, wie du alles eingestellt hast?

**Comment by Tylli** [comment]
> [{"id":"b5d1c1a7.855ca","type":"tab","label":"Homebridge","disabled":false,"info":""},{"id":"d4092763.1503e8","type":"redmatic-homekit-homematic-devices","z":"b5d1c1a7.855ca","ccuConfig":"38263145.35ea0e","bridgeConfig":"95354d5e.74a63","devices":{"0000D3C9995ACE:1":{"type":"ContactSensor","disabled":false},"0000D3C9997FFD:1":{"type":"ContactSensor","disabled":false},"0000D7099588DF:1":{"type":"ContactSensor","disabled":false},"0000D709A143B2:1":{"type":"ContactSensor","disabled":false}},"x":140,"y":100,"wires":[]},{"id":"c011d012.80333","type":"inject","z":"b5d1c1a7.855ca","name":"Set Min/Max","topic":"0/TargetTemperature","payload":"{\"minValue\":-20, \"maxValue\":60}","payloadType":"json","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":150,"y":160,"wires":[[]]},{"id":"acbe7f60.dc0aa","type":"dyson-link","z":"b5d1c1a7.855ca","confignode":"37d67035.56019","device":"Schlafzimmer","deviceserial":"VS9-EU-MNA3479A","action":"getTemperature","value":0,"x":420,"y":240,"wires":[["9684aaf3.39eb88"]]},{"id":"233d5ebc.337fa2","type":"debug","z":"b5d1c1a7.855ca","name":"Temperatur","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":930,"y":480,"wires":[]},{"id":"9684aaf3.39eb88","type":"change","z":"b5d1c1a7.855ca","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"0/CurrentTemperature","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"payload.temperature","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":620,"y":240,"wires":[["233d5ebc.337fa2","75467c48.2e8354"]]},{"id":"d18b505a.d7dc4","type":"dyson-link","z":"b5d1c1a7.855ca","confignode":"37d67035.56019","device":"Schlafzimmer","deviceserial":"VS9-EU-MNA3479A","action":"getRelativeHumidity","value":0,"x":420,"y":300,"wires":[["90305f42.accd3"]]},{"id":"bb358a82.fc4998","type":"debug","z":"b5d1c1a7.855ca","name":"Luftqualität","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":930,"y":520,"wires":[]},{"id":"90305f42.accd3","type":"change","z":"b5d1c1a7.855ca","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"0/CurrentRelativeHumidity","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"payload.relative_humidity","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":620,"y":300,"wires":[["bb358a82.fc4998","46b36022.e04ad"]]},{"id":"33528f50.86cfd","type":"dyson-link","z":"b5d1c1a7.855ca","confignode":"37d67035.56019","device":"Schlafzimmer","deviceserial":"VS9-EU-MNA3479A","action":"getAirQuality","value":0,"x":420,"y":360,"wires":[["47820aaa.9edf24"]]},{"id":"47820aaa.9edf24","type":"change","z":"b5d1c1a7.855ca","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.air_quality","tot":"msg"},{"t":"set","p":"topic","pt":"msg","to":"0/AirQuality","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":620,"y":360,"wires":[["16b5ff6c.dbf781","ba726342.2be11"]]},{"id":"16b5ff6c.dbf781","type":"debug","z":"b5d1c1a7.855ca","name":"Luftqualität","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":930,"y":580,"wires":[]},{"id":"c0e522fd.2cfea","type":"inject","z":"b5d1c1a7.855ca","name":"","topic":"","payload":"","payloadType":"date","repeat":"300","crontab":"","once":true,"onceDelay":0.1,"x":150,"y":300,"wires":[["acbe7f60.dc0aa","d18b505a.d7dc4","33528f50.86cfd"]]},{"id":"3591ee63.e8d452","type":"dyson-link","z":"b5d1c1a7.855ca","confignode":"37d67035.56019","device":"Schlafzimmer","deviceserial":"VS9-EU-MNA3479A","action":"getFanStatus","value":0,"x":420,"y":420,"wires":[["8cc5c6e5.f2efe8"]]},{"id":"9baef3ff.7ccbd","type":"debug","z":"b5d1c1a7.855ca","name":"FanStatus","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":930,"y":640,"wires":[]},{"id":"8cc5c6e5.f2efe8","type":"change","z":"b5d1c1a7.855ca","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.fan_status","tot":"msg"},{"t":"set","p":"topic","pt":"msg","to":"3/CurrentFanState","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":"true","fromt":"bool","to":"On","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":620,"y":420,"wires":[["9baef3ff.7ccbd"]]},{"id":"46b36022.e04ad","type":"redmatic-homekit-universal","z":"b5d1c1a7.855ca","bridgeConfig":"95354d5e.74a63","name":"Luftfeuchtigkeit","services":[{"subtype":"0","service":"HumiditySensor","name":"Feuchtigkeit"}],"x":940,"y":300,"wires":[[]]},{"id":"75467c48.2e8354","type":"redmatic-homekit-universal","z":"b5d1c1a7.855ca","bridgeConfig":"95354d5e.74a63","name":"Temperatur","services":[{"subtype":"0","service":"TemperatureSensor","name":"Temperatur"}],"x":930,"y":240,"wires":[[]]},{"id":"ba726342.2be11","type":"redmatic-homekit-universal","z":"b5d1c1a7.855ca","bridgeConfig":"95354d5e.74a63","name":"Luftqualität","services":[{"subtype":"0","service":"AirQualitySensor","name":"Luftqualität"}],"x":930,"y":360,"wires":[[]]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048"},{"id":"95354d5e.74a63","type":"redmatic-homekit-bridge","z":"","name":"RedMatic Bridge","username":"CC:22:3D:DE:F5:29","pincode":"013-36-599","port":"51826"},{"id":"37d67035.56019","type":"dyson-config","z":"","username":"alextylkowski@me.com","password":"Aliidrive1","country":"DE"}]


![image](https://user-images.githubusercontent.com/67158524/85172959-7bb9a000-b272-11ea-81e7-30d1d5e0ec5b.png)

Habe etwas umgebaut, damit ich die Infos einzeln in Homekit habe, aber das ist für dich ja unerheblich.

**Comment by Tylli** [comment]
[{"id":"acbe7f60.dc0aa","type":"dyson-link","z":"b5d1c1a7.855ca","confignode":"37d67035.56019","device":"Schlafzimmer","deviceserial":"VS9-EU-MNA3479A","action":"getTemperature","value":0,"x":420,"y":240,"wires":[["9684aaf3.39eb88"]]},{"id":"233d5ebc.337fa2","type":"debug","z":"b5d1c1a7.855ca","name":"Temperatur","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":930,"y":480,"wires":[]},{"id":"9684aaf3.39eb88","type":"change","z":"b5d1c1a7.855ca","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"0/CurrentTemperature","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"payload.temperature","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":620,"y":240,"wires":[["233d5ebc.337fa2","75467c48.2e8354"]]},{"id":"d18b505a.d7dc4","type":"dyson-link","z":"b5d1c1a7.855ca","confignode":"37d67035.56019","device":"Schlafzimmer","deviceserial":"VS9-EU-MNA3479A","action":"getRelativeHumidity","value":0,"x":420,"y":300,"wires":[["90305f42.accd3"]]},{"id":"bb358a82.fc4998","type":"debug","z":"b5d1c1a7.855ca","name":"Luftqualität","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":930,"y":520,"wires":[]},{"id":"90305f42.accd3","type":"change","z":"b5d1c1a7.855ca","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"0/CurrentRelativeHumidity","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"payload.relative_humidity","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":620,"y":300,"wires":[["bb358a82.fc4998","46b36022.e04ad"]]},{"id":"33528f50.86cfd","type":"dyson-link","z":"b5d1c1a7.855ca","confignode":"37d67035.56019","device":"Schlafzimmer","deviceserial":"VS9-EU-MNA3479A","action":"getAirQuality","value":0,"x":420,"y":360,"wires":[["47820aaa.9edf24"]]},{"id":"47820aaa.9edf24","type":"change","z":"b5d1c1a7.855ca","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.air_quality","tot":"msg"},{"t":"set","p":"topic","pt":"msg","to":"0/AirQuality","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":620,"y":360,"wires":[["16b5ff6c.dbf781","ba726342.2be11"]]},{"id":"16b5ff6c.dbf781","type":"debug","z":"b5d1c1a7.855ca","name":"Luftqualität","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":930,"y":580,"wires":[]},{"id":"c0e522fd.2cfea","type":"inject","z":"b5d1c1a7.855ca","name":"","topic":"","payload":"","payloadType":"date","repeat":"300","crontab":"","once":true,"onceDelay":0.1,"x":150,"y":300,"wires":[["acbe7f60.dc0aa","d18b505a.d7dc4","33528f50.86cfd"]]},{"id":"3591ee63.e8d452","type":"dyson-link","z":"b5d1c1a7.855ca","confignode":"37d67035.56019","device":"Schlafzimmer","deviceserial":"VS9-EU-MNA3479A","action":"getFanStatus","value":0,"x":420,"y":420,"wires":[["8cc5c6e5.f2efe8"]]},{"id":"9baef3ff.7ccbd","type":"debug","z":"b5d1c1a7.855ca","name":"FanStatus","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":930,"y":640,"wires":[]},{"id":"8cc5c6e5.f2efe8","type":"change","z":"b5d1c1a7.855ca","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.fan_status","tot":"msg"},{"t":"set","p":"topic","pt":"msg","to":"3/CurrentFanState","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":"true","fromt":"bool","to":"On","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":620,"y":420,"wires":[["9baef3ff.7ccbd"]]},{"id":"46b36022.e04ad","type":"redmatic-homekit-universal","z":"b5d1c1a7.855ca","bridgeConfig":"95354d5e.74a63","name":"Luftfeuchtigkeit","services":[{"subtype":"0","service":"HumiditySensor","name":"Feuchtigkeit"}],"x":940,"y":300,"wires":[[]]},{"id":"75467c48.2e8354","type":"redmatic-homekit-universal","z":"b5d1c1a7.855ca","bridgeConfig":"95354d5e.74a63","name":"Temperatur","services":[{"subtype":"0","service":"TemperatureSensor","name":"Temperatur"}],"x":930,"y":240,"wires":[[]]},{"id":"ba726342.2be11","type":"redmatic-homekit-universal","z":"b5d1c1a7.855ca","bridgeConfig":"95354d5e.74a63","name":"Luftqualität","services":[{"subtype":"0","service":"AirQualitySensor","name":"Luftqualität"}],"x":930,"y":360,"wires":[[]]},{"id":"37d67035.56019","type":"dyson-config","z":"","username":"ANMELDENAME","password":"PASSWORT","country":"DE"},{"id":"95354d5e.74a63","type":"redmatic-homekit-bridge","z":"","name":"RedMatic Bridge","username":"CC:22:3D:DE:F5:29","pincode":"013-36-599","port":"51826"}]

**Comment by Tylli** [comment]
![Unbenannt3](https://user-images.githubusercontent.com/67158524/85173209-f84c7e80-b272-11ea-9406-4a3c6eaa0c21.png)

Habe etwas umgebaut, damit ich die Infos einzeln in Homebridge habe aber das ist für dich ja unerheblich.

**Comment by ldiekmann** [comment]
Vielen Dank.
Ich habe es mal bei mir eingepflegt. Leider ohne Erfolg.

Ich habe beim Dyson-Link meine Clouddaten eingegeben. Ich kann nicht mal mein Gerät aus wählen. Er sucht, findet aber nichts. Das hatte ich auch schon zwischendurch bei meinem Flow.

Des weiteren bekomme ich folgende Fehlermeldung im Debug.
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

Vielleicht kannst du etwas damit anfangen.

**Comment by Tylli** [comment]
Also, was bei mir scheinbar was gebraucht hat ist die Anmeldedaten des Dyson Link im Node komplett zu löschen und sie dann neu einzutragen.

Hast du irgendwelche Abfragen, welche sekündlich oder so stattfinden? Ich habe eben mal den Test gemacht. Ich habe das Abfrageintervall auf 1 Minute gestellt und alles funktioniert. Sobald ich die Abfrage 3-4 mal hintereinander per Hand starte kommen keine Nachrichten mehr.

**Comment by ldiekmann** [comment]
Guten morgen.
Ich habe jetzt noch einmal probiert mein Gerät auszuwählen. Das funktioniert auch soweit. Leider bekomme ich aber keine Werte. So wie im Screenshot habe ich es nun angelegt. Sollte doch identisch mit deinem sein. Im Debug zeigt er mir aber nichts an. Muss man den Timestamp anstoßen oder startet der automatisch nach der eingestellten Zeit (5 Minuten)?
Anbei noch ein Screenshot von meinem aktuellen Flow. Wenn das läuft, würde ich den nächsten Schritt mit dem Steuern probieren. Ich habe nur gelesen, das man irgendetwas mit msg.payload.action machen muss.
![Bildschirmfoto 2020-06-20 um 07 08 47](https://user-images.githubusercontent.com/67023005/85192995-396d7e80-b2c5-11ea-8683-7a7a5a21b8f7.png)

**Comment by Tylli** [comment]
Der Timestamp sollte nach Aktivierung und dann alle 5 Minuten eine Abfrage starten. Du kannst diese aber auch Manuell anstoßen mit einem Druck auf die blaue Fläche. Sind die Debugs auf „.msg“ gestellt oder auf vollständige Nachricht? Du solltest das Zweite anwählen. Ansonsten trenne testweise mal die Verbindung zu zwei Dyson Nodes und nimm nur Temperatur. Dann deaktiviere die automatische Abfrage und warte eine Stunde (eine echte! Stunde). Dann drückst du auf die blaue Schaltfläche.

Es scheint wirklich so als wenn die Abfragen pro Zeiteinheit Probleme machen und der Account ausgesetzt wird. Die Abfrage der App geht so weit ich gelesen habe über einen anderen Kanal als die Node, daher funktioniert das Eine, das Andere aber nicht.

**Comment by ldiekmann** [comment]
Danke für die Info mit dem Timestamp.

Ich werde mein Glück mal mit der Stunde Pause versuchen und berichten.

**Comment by Tylli** [comment]
Habe jetzt ebenfalls mit einem Switch gespielt. Es funktioniert 5 Mal hintereinander, danach ist Schluss. Keine Antworten mehr.

**Comment by ldiekmann** [comment]
Ich habe es jetzt noch mal probiert. Leider ohne Erfolg.
Ich habe jetzt alles mal gelöscht und versuche es morgen noch mal.

**Comment by Tylli** [comment]
So, mal ein Update. 

Ich habe ein wenig recherchiert und es scheint wirklich eine Art Time-Out zu geben. Ich habe mich zwischenzeitlich von Node-Red verabschiedet und bin auf Homebridge umgestiegen. Hier gibt es ein Plugin, welches anders arbeitet als diese Node.

Bei der ersten Anfrage an die Dyson Cloud wird ein Schlüssel abgesprochen, welcher die Kommunikation herstellt. Die Node scheint diesen Schlüssel bei jeder Abfrage neu an die Cloud zu senden. In Homebridge kann ich den Schlüssel bei der ersten Abfrage auslesen und ihn dann in das Plugin einfügen. Die Abfragen gehen dann über das interne Netzwerk mit dem Schlüssel direkt zum Gerät und nicht über die Cloud.

Wenn man das Plugin nicht mit dem Schlüssel ausstattet, dann sendet es zwar Anfragen aber immer mit einem Zeitversatz von 6 Minuten! Um eben dem Timeout aus dem Weg zu gehen.

Diese Node bräuchte natürlich einen massiven Umbau um das zu bewerkstelligen. Hier einmal das Plugin, welches ich jetzt nutze:

https://www.npmjs.com/package/homebridge-dyson-pure-cool

Vielleicht kannst du damit ja was anfangen.

**Comment by ldiekmann** [comment]
Hallo,
danke für die Info. Worauf lässt du die Homebridge laufen. Da habe ich noch keine Erfahrungen mit.
Ich werde mal schauen ob ich das bei mir implementieren kann.
Klingt auf jedenfall interessant

**Comment by ldiekmann** [comment]
Ich habe nun die Homebridge mit GUI bei mir installiert. Das Dyson Plugin habe ich auch installiert. Kannst du mir ab da weiterhelfen? Wie bekomme ich nun "Verknüpfungen" hin? Steuern/Auslesen?

**Comment by naimo84** [comment]
Hallo zusammen,

ich habe ebenfalls etwas umgebaut. Wenn ihr die IP von euren Geräten wisst, könnt ihr diese nun in die Node eintragen. Die Verbindung zur Cloud wird nur am Anfang benötigt, um das Passwort zu erfragen. Der Rest läuft dann (wie übrigens schon immer) nur lokal über den MQTT Server der Devices. Die von Dyson haben scheinbar etwas geändert mit einem der letzten Updates.... Bin noch auf der Suche, was genau.

Nichts desto trotz gibt es scheinbar tatsächlich einen Timeout bei den Anfragen. Dies ist mir beim initialen Codieren auch schon aufgefallen. Bisher habe ich aber noch keine anständige Lösung dafür gefunden. Außer die Abfragen eben nicht sekündlich, sondern minütlich zu machen.

Und sorry für die späte Antwort. "Corona sei dank", haben wir momentan einen Haufen Berg Arbeit hier :/

Viele Grüße,
Benjamin

**Comment by ldiekmann** [comment]
Hallo Benjamin,

wo kann ich die IP-Adresse denn eintragen?

Viele Grüße zurück,
Lars

**Comment by naimo84** [comment]
Hallo Lars,

ab Version 0.2.0 direkt im Node.

![image](https://user-images.githubusercontent.com/11535502/85321762-80c25d80-b4c5-11ea-92db-f98bfb2ab29f.png)

Evtl dauert es noch ein wenig bis die Version bei dir im nodeRed auftaucht. So ganz hab ich den UpdateMechanismus von nodeRed auch nach einem Jahr nodeEntwicklung noch nicht verstanden 😉 

Grüße,
Benjamin

**Comment by ldiekmann** [comment]
Hallo Benjamin,
ich habe nun ein Update auf das neue Node machen können. Das Feld für die IP Adresse ist nun auch da.
Ich bekomme aber keine Kommunikation hin. Kannst du mir ein Beispiel zu kommen lassen?

Gruß
Lars

**Comment by Tylli** [comment]
Moin Benjamin, Moin Lars,
Ich habe jetzt seit 3 Tagen das oben genannte Plugin in Betrieb mit der Homebridge. Es funktioniert ohne Probleme. Habe den Dyson jetzt mal testweise ständig schneller und langsamer gestellt und es funktioniert dauerhaft.

Der einzige Unterschied den ich feststellen kann ist, dass ich die „Credentials“ also den Schlüssel nach dem ersten aktivieren aus dem Log kopieren musste um ihn in der Config zu speichern. Speichert die Node automatisch? Es muss ja einen Grund geben, dass ich das per Hand eintragen muss. Ich weiß aber nicht ob es bei Homebridge vielleicht nicht möglich ist, dass ein Plugin ins die Config schreibt.

**Comment by ldiekmann** [comment]
Moin Tylli,
ich habe es nun nochmal mit der Homebridge versucht. Ich habe die Credentials aus dem Log in die Einstellungen von dem Plugin kopiert. Leider bekomme ich immer noch keine Werte und Ansteuerung hin.
Kannst du mir da weiter helfen? Ich weiß leider nicht was ich falsch mache.
Gruß Lars

**Comment by ldiekmann** [comment]
Ich habe gerade noch mal geschaut. Bei den Geräten zeigt er mir folgendes an.
![Bildschirmfoto 2020-06-24 um 20 13 47](https://user-images.githubusercontent.com/67023005/85610554-65875780-b657-11ea-9b1a-1d1940ed6cdf.png)

**Comment by ldiekmann** [comment]
Moin Benjamin, Moin Tylli,
leider komme ich mit Node Red als auch mit Homebridge nicht weiter. Kann mir da einer von euch helfen? Ich bin am verzweifeln.

**Comment by Tylli** [comment]
Hey!
Ich bin derzeit arg eingespannt und hab mit zusätzlich die Woche noch den Fuß gebrochen. Bin morgen zu Hause und dann suchen wir eine Lösung!

Nutzt du denn jetzt Node oder das Homebridge Plugin? Bin bei dem Homebridge Plugin geblieben und habe nicht einen Aussetzer seit dem gehabt!

**Comment by ldiekmann** [comment]
Hey,
ich wollte auch gar nicht drängeln. Hatte mich nur gewundert, dass auf einmal "Funkstille" herrschte.
Auf diesem Wege erst mal gute Besserung.

Schon mal vielen Dank für deine Unterstützung.
Ich nutze aktuell das Homebridge Plugin. Welcher Weg, ist mir eigentlich gleich. Im Node habe ich den Inhalt von dem Flow gelöscht und die Konfiguration vom Dyson auch. Habe ich hier ggf. noch etwas vergessen, was stören könnte?

**Comment by naimo84** [comment]
Hallo ihr beiden,

tut mir leid, dass ich zu keiner Lösung beitragen konnte...

Die Einrichtung der Homebridge aber bitte dann wo anders weiterführen.

Danke und viele Grüße,
Benjamin

@Tylli: Gute Besserung!

**Comment by ldiekmann** [comment]
Hallo Benjamin,
ich habe mich nun endgültig für Node Red entschieden. Das Auslesen funktioniert auch einwandfrei. Kann man auch die Lüftergeschwindigkeit auslesen? Ich bekomme nur die Werte, welche Tylli auch mal als Flow zur verfügung gestellt hat.

Wie steuere ich nun den Dyson an? Ich probiere es schon den ganzen Tag. Es scheitert wahrscheinlich an einer Kleinigkeit.

Vielen Dank im Voraus
Gruß Lars
