### ISSUE TITLE
AirQuality Value

### ISSUE THREAD

**Issue by Tylli** [naimo84/node-red-contrib-dyson-purelink#15]
Hi! How do you get the AirQuality value? I see you take the value of dust and voc and add them to another. Then you divide them by 2 and multiply with the sensitivity. The problem is that I get 5 almost everytime although the value in the Dyson app is 2. 

I‘m using the Dyson Pure & Cool Tower and I can‘t define a sensitivity value there. Maybe it is possible to get the value directly from the Dyson cloud?

         airQuality = Math.min(Math.max(Math.floor((dustValue + vocValue) / 2 * this.sensitivity), 1), 5)

**Comment by naimo84** [comment]
Hi,

i refactored my code with some code of Lukas Roegner and his great homebridge module ;) 
https://github.com/lukasroegner/homebridge-dyson-pure-cool/blob/2cb1d31919a3b7b4513c22954ae4ae56da8e7136/src/dyson-pure-cool-device.js#L432

So may you please have a look at v0.1.7?

Greets,
Benjamin
