### ISSUE TITLE
Functions randomly not working/documentation lacking for less experienced users

### ISSUE THREAD

**Issue by koshisan** [naimo84/node-red-contrib-dyson-purelink#16]
Hi,
I didn't really know where to put this, so I filed it as a bug (as suggested by the contribution-document).

I am trying to get my Dyson Hot and Cool running (through openhab->node-red), but wasn really successful so far:

* I was able to turn the device on/off with the "turn On" "turn Off" function. Sometimes after restarting node-red this does not work - the commands are just ignored. I have entered the IP adress of the device and the configuration of the node seems to be ok, since all devices (I have two in total) are correctly discovered/changes in the name are instantly reflected
* I was not able to control the rotation. The documentation says setRotation in msg.payload.rotation _must_ be set. However, there seems to be the possibility to supply a "Value" throug the gui? Though format and possible values are unknown. Setting it to "1" seems to enable rotation, disabling setting it to zero was unsuccessful, however...
* I was also not able to control the fan speed. Same problem as above.

Also I am not sure how to exactly provide the values msg.payload.rotation and msg.payload.speed. The speed value for example is stored in an OpenHab String, so it is passed directly as the payload. While I can overwrite the payload itself with a function using a "payload: false" statement for example, "payload.speed: 5" gives an syntax error... I think it would be really helpful if real node examples would be given in the documentation...

Thanks a lot!

**Comment by ldiekmann** [comment]
Hello Koshisan,

I have a similar behavior with the Dyson Pure cool link. I had been able to read measured values for a while. Then I wanted to control the Dyson. Now nothing works anymore. I have no idea what it could be.
Greetings Lars

@naimo84: maybe you have a flow as an example for us?

**Comment by koshisan** [comment]
That is an interesting way of handling bug reports. If the bug is ignored long enough, the report is closed so other people won't find it...

**Comment by naimo84** [comment]
I'm sorry about, what happened here. I have a wife, a one year old daughter, a very time consuming full time hob, covid-19,... so all this leaded to very less spare time and even more less time for maintaining/coding nodered-nodes. It's not just ignoring.... I try to add examples as soon as possible

**Comment by koshisan** [comment]
No problem, of course I get that you do the development for free in your spare time, so it is completely out of line to make any remarks about speed, etc. I am very grateful for your work!
It's more the general process on github's side I was unsatisfied - automatically closing issues through a bot just because there has been no update for a while...
(I was only checking back because I recieved an additional fan today so I will try again with the smarthome integration over the weekend)

**Comment by hendersj** [comment]
I've got a similar issue going on here - I had things working until a few days ago, and now I'm not getting any connection to my fan.  My flow seems to stop when the dyson link node executes.  Not sure how to debug what's going on, but willing to do what I can.

I'm running node-red 1.2.2 in a Docker container.  My flow creates an API endpoint that I use in conjunction with IFTTT.  I've confirmed connectivity with the Dyson website (login credentials are correct) and that the fan can be reached on the network (the Android app works fine with it).

**Comment by hendersj** [comment]
Just commenting to note that this is still an intermittent issue here.  I know that the maintainer has probably had life stuff going on - no big deal.  Just wanted to make sure the issue stayed open until someone had a chance to look into it. :)
