### ISSUE TITLE
Nodes not working at all

### ISSUE THREAD

**Issue by nicedevil007** [naimo84/node-red-contrib-dyson-purelink#19]
Hey naimo84 :)

nun wieder einmal etwas von dir entdeckt nach deiner tollen Arbeit für PiHole, hehe.

Habe versucht den Dyson hier reinzukriegen.

Fehlerlog sieht aktuell so aus:

```
(node:16) UnhandledPromiseRejectionWarning: StatusCodeError: 429 - "{error: \"Endpoint is not available currently\"}",
    at Request.plumbing.callback (/data/node_modules/request-promise-core/lib/plumbing.js:104:33),
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22),
    at new StatusCodeError (/data/node_modules/request-promise-core/lib/errors.js:32:15),
    at Request.self.callback (/data/node_modules/request/request.js:185:22),
    at Request.RP$callback [as _callback] (/data/node_modules/request-promise-core/lib/plumbing.js:46:31),
    at Request.emit (events.js:314:20),
    at Request.<anonymous> (/data/node_modules/request/request.js:1154:10),
    at IncomingMessage.<anonymous> (/data/node_modules/request/request.js:1076:12),
    at Object.onceWrapper (events.js:420:28),
    at IncomingMessage.emit (events.js:326:22)
```

Übrigens habe ich viel weiter oben im log auch meine Zugangsdaten im Klartext im log gefunden, ist das im Sinne des Erfinders?

**Comment by nicedevil007** [comment]
Hab noch bissl getestet, also es sieht so aus, dass dieser Fehler passiert, sobald man irgendwas mehr wie 5-7 deiner Nodes platziert hat. Hab jetzt gerade 2 stück für Temp und 2 Stück für Luftfeuchte drin.

Gibts ne Möglichkeit, dass du das alles über 1 Node wieder steuern lassen könntest, also dass ich mit nem eingehenden object festlege was ich alles haben möchte?

Also sowas wie: 

msg.payload = "get" => er spuckt alles aus, was man mit get kriegen könnte => vorzugsweise in einem einzigen payload der als object aufgebaut ist

msg.payload = {"action": "set", "setting": "Heater On"} => man gibt ihm das setting als object mit z.b.

turn on / turn off würde ich auch unter "set" mit sehen.

Was hälst davon?

**Comment by naimo84** [comment]
Hey nicedevil,

danke für deine netten Worte :) ich versuch mal, was ich tun kann ;) 

Heute morgen hab ich erst die README etwas angepasst, das geht wohl auch schon ein wenig in die Richtung wie du im zweiten Post beschrieben hast. Das ging schon immer, ich hab's nur nirgends beschrieben....

Also z.B. msg.payload = { "action": "setFanSpeed","speed": "100" } setzt den FanSpeed auf 100%
msg.payload = { "action": "getFanStatus" } gibt zurück ob an oder aus.
usw.

Was ich noch nicht fertig bekommen habe ist, mehrere Dyson über die IP anzusteuern. Da ich auch leider nur einen besitze, muss ich mir noch überlegen, wie ich das testen kann.

Ich bitte allerdings um etwas Geduld ;) Momentan sind die freien Minuten sehr begrenzt...

Grüße,
Benjamin

**Comment by nicedevil007** [comment]
Haha, alles klar, ich stelle mich gern als Tester zur Verfügung, hätte hier mehr wie 2 Hände voll Dysons zum auslesen und steuern.

Die IP Adresse für das Gerät kann man net mit über nen object übergeben? Dat wäre spitze.

**Comment by hammerandpick** [comment]
Habe leider genau das oben beschriebene Ptoblem auch festgestellt. Zuerst konnte ich die Daten auslesen, aber nachdem ich so ca. 4-5 plaziert hatte war es damit vorbei.
