### ISSUE TITLE
Node not communicating

### ISSUE THREAD

**Issue by forry2** [naimo84/node-red-contrib-dyson-purelink#2]
Hi sir,

excellent product for NodeRED.. I find myself not able to make it work though. Here is my flow:

[{"id":"e6babaf.08e4348","type":"tab","label":"test","disabled":false,"info":""},{"id":"d0a9fcc3.0605a","type":"dyson-link","z":"e6babaf.08e4348","confignode":"16b72c43.3c3aec","device":"1","deviceserial":"","action":"getTemperature","value":0,"x":360,"y":220,"wires":[["2dbcd57b.6680e2"]]},{"id":"2dbcd57b.6680e2","type":"debug","z":"e6babaf.08e4348","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":610,"y":300,"wires":[]},{"id":"b8be35d7.ae246","type":"inject","z":"e6babaf.08e4348","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":160,"y":300,"wires":[["d0a9fcc3.0605a"]]},{"id":"16b72c43.3c3aec","type":"dyson-config","z":"","username":"robeXXXXXXXXXX@gmail.com","password":"XXXXXXXXXX","country":"IT"}]

I put an Inject node to have something out of your Dyson node, but nothing seems to come out. Would you please help me out in understanding what's wrong with it?
Plus, the list of devices is not selectable, it looks as though it's read-only: I do see my Dyson device, but I am not able to select it

**Comment by naimo84** [comment]
Hi forry2,

if you see your device in the list, the connection to the dyson cloud is working. 
The communication with the device itself works through MQTT in your network.

What dyson device are you using? Do you know the IP address of the device? Then you could try to connect via MQTT.

Best regards, 
Benjamin

**Comment by forry2** [comment]
Ciao Benjamin, thank you so much for hitting me back on this!
You mean I have to configure your node as an MQTT reader out of a topic?
How do I find what topic my Dyson device is writing to?
I have a pure hot+cold device, but I don't know how to find its IP address

[image: immagine.png]


Il giorno mer 29 gen 2020 alle ore 07:47 Benjamin <notifications@github.com>
ha scritto:

**Comment by naimo84** [comment]
Hi again,
no you don't have to configure my node as a mqtt reader. But there some Windows and Linux tools for connecting to the dyson device, without nodered at all. That would be just for testing the connection. 

Do you have a pure hot & cool or a pure hot & cool link. The link version is necessary for my nodes. Without link, the devices Do not have a mqtt server onboard.
If it's the link version, please check if wifi is enabled on it. 

Greets to italy, 
Benjamin

**Comment by forry2** [comment]
Benji

That's the one in the attached pic

**Comment by naimo84** [comment]
Hi Forry,

unfortunately I don't see a pic, neither here nor in the email 😉 

Ciao,
Benjamin

**Comment by forry2** [comment]
https://www.google.com/aclk?sa=l&ai=DChcSEwiQ-fSq6rTnAhWS53cKHdPrBWwYABABGgJlZg&ae=1&sig=AOD64_3EryxK-18QP2olU3YWQE1CAFlqgw&adurl=https://shop.dyson.it/ventilatori-e-termoventilatori-dyson/purificatori/dyson-pure-hot-cool-bianco-244280-01?utm_campaign%3Dit_it__environmental__heaters__do__dyson__pure_hot_cool__consideration__shopping__all__na%26utm_source%3Dgoogle%26utm_medium%3Dpaid_search%26utm_term%3DPRODUCT_GROUP%26utm_content%3Dds_na%26gclsrc%3Daw.ds%26%26gclid%3DCjwKCAiAg9rxBRADEiwAxKDTugdEnfAPT25rcLrV7hmjJhWagofx0G6Ly-pXHbPI_wMWrglcEDjvnBoC0RsQAvD_BwE&ctype=5&ved=2ahUKEwjck-qq6rTnAhUoo7QKHdd-AwcQwg96BAgBEB4

**Comment by forry2** [comment]
Let me go and try again :)
This is the one I have, I pasted the picture within this email
[image: immagine.png]

**Comment by naimo84** [comment]
Hey Forry,

theoretically your device has an internal mqtt-server. Do you have activated the WiFi on your device? Can you control via an android or iOS App?

Greetings, 
Benjamin

**Comment by forry2** [comment]
Ciao Benjiamin

Yes, WiFi is active... I can contro my device remotrly, from within my
network and from the public internet, with the Dyson app

Roberto

**Comment by naimo84** [comment]
Ciao Roberto,

then it's hard to find your bug. Can you try to find the IP adress of your device? From the gui of your router perhaps?
Then we can try to connect with another mqtt client to it.

Greets,
Benjamin

**Comment by forry2** [comment]
Will surely do! Thanks for now!
