### ISSUE TITLE
Adapt to "Dyson Purifier Humidify + Cool Formaldehyde Humidifier White / Gold"

### ISSUE THREAD

**Issue by gitmors** [naimo84/node-red-contrib-dyson-purelink#39]
Hi there,

I have a new dyson "Dyson Purifier Humidify + Cool Formaldehyde Humidifier White / Gold" device. Would it be possible to adapt the program to this device? Unfortunately, I can't even turn it off and on. The temperature can be read out and the rotation can also be switched on and off.

setRotation and get rotation are also possible.

I once did a trace with wireshark and with it I got the following read out.
There are two MQTT packages returned:

M9F-EU-serialnumber/status/current{"msg":"CURRENT-STATE","time":"2021-12-08T12:05:57.000Z","mode-reason":"PRC","state-reason":"MODE","rssi":"-52","channel":"5","fqhp":"104144","fghp":"72848","product-state":{"fpwr":"ON","auto":"OFF","oscs":"ON","oson":"ON","nmod":"OFF","rhtm":"OFF","fnst":"FAN","ercd":"NONE","wacd":"NONE","nmdv":"0004","fnsp":"0001","bril":"0002","corf":"ON","cflr":"INV","hflr":"0099","cflt":"SCOF","hflt":"GCOM","sltm":"OFF","osal":"0189","osau":"0189","ancp":"0090","hume":"HUMD","haut":"ON","humt":"0070","rect":"0045","msta":"OFF","clcr":"CLNO","cdrr":"0060","cltr":"0671","wath":"0675","psta":"OFF","fdir":"ON"},"scheduler":{"srsc":"0000000000000000","dstv":"0001","tzid":"0001"}}

+

M9F-EU-serialnumber/status/current{"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","time":"2021-12-08T12:05:57.000Z","data":{"tact":"2947","hact":"0049","pm25":"0000","pm10":"0000","va10":"0005","noxl":"0003","p25r":"0001","p10r":"0001","hcho":"0004","hchr":"0011","sltm":"OFF"}}

For on and off, for example, I think the command "**fpwr**" would have to be used instead of "**fmod**".

Unfortunately, the commands cannot be passed on 1: 1, so the program must be adapted.

The table from the ioBroker project seems to me to be quite complete.

Thank you very much for your help.

<html>
<body>
<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">CURRENT-STATE</h3>

name | meaning | possible values | Unit
-- | -- | -- | --
mode-reason | Current Mode has been set by RemoteControl, App, Scheduler | PRC, LAPP, LSCH, PUI |  
state-reason |   | MODE |  
rssi | WIFI Strength | -100 - 0 | dBm
channel | WIFI Channel | 52 |  
fqhp |   | 96704 |  
fghp |   | 70480

</body>
</html>

<html>
<body>
<h4 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 16px; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">product-state</h4>

name | meaning | possible values | Unit
-- | -- | -- | --
ercd | Last Error Code | NONE , or some hexa values |  
filf | remaining Filter life | 0000 - 4300 | hours
fmod | Mode | FAN , AUTO, OFF |  
fpwr | Main Power | ON, OFF |  
fnst | Fan Status | ON , OFF, FAN |  
fnsp | Fan speed | 0001 - 0010, AUTO |  
fdir | Fandirection aka. Jet focus/ ON=Front, OFF=Back | ON, OFF |  
ffoc | JetFocus | ON, OFF |  
nmod | Night mode | ON , OFF |  
oson | Oscillation | ON , OFF |  
osal | OscillationAngle Lower Boundary | 0005 - 355 | ° (degrees)
osau | OscillationAngle Upper Boundary | 0005 - 355 | ° (degrees)
oscs | OscillationActive | ON, OFF, IDLE |  
ancp | OscillationAngle | CUST, 0180 | ° (degrees)
qtar | Air Quality target | 0001=Good, 0002=Normal, 0003=Bad, 0004=Very bad |  
rhtm | Continuous Monitoring | ON, OFF |  
auto | AutomaticMode | ON, OFF |  
nmdv | NightMode Max Fanspeed? | 0004 |  
cflr | Status Carbonfilter | 0000 - 0100 | Percent
cflt | Carbonfilter | CARF, NONE |  
hflr | Status HEPA-Filter | 0000 - 0100 | Percent
hflt | HEPA-Filter | GHEP, GCOM |  
sltm | Sleeptimer | ON, OFF |  
hmod | Heater Mode [ON/OFF] | HEAT |  
hmax | Target temperature for heating | 0 .. 5000 | K
hume | HumidificationMode | ON, OFF, |  
haut | Humidify Auto Mode | HUMIDIFY_AUTO_MODE_ON, HUMIDIFY_AUTO_MODE_OFF |  
humt | Humidification Target | HUMIDIFICATION_MODE_OFF, HUMIDIFICATION_MODE_THIRTY, HUMIDIFICATION_MODE_FORTY, HUMIDIFICATION_MODE_FIFTY, HUMIDIFICATION_MODE_SIXTY, HUMIDIFICATION_MODE_SEVENTY |  
cdrr | CleanDurationRemaining | integer | minutes
rect | AutoHumidificationTarget | integer | %
cltr | TimeRemainingToNextClean | integer | hours
wath | WaterHardness | SOFT="2025", MEDIUM="1350", HARD="0675" |  
wacd | WarningCode | NONE... |  
rstf | reset filter lifecycle | 'RSTF', 'STET', RESET_FILTER_LIFE_IGNORE, RESET_FILTER_LIFE_ACTION |  
corf | Temperature format | ON=Celsius, OFF=Fahrenheit |  
clcr | DeepcleanCycle | CLNO=inactive, CLAC=Deep clean in progress, CLCM=Finished |  
hsta | Heating state | ACTIVE/IDLE |  
msta | Humidification state | Active/Idle OFF, HUMD |  
psta | [HP0x] Unknown | INIT, CLNG, INV, OFF |  
bril | unknown | 0002 | LEVEL_LOW, LEVEL_MEDIUM, LEVEL_HIGH
fqhp | unknown |   |  
tilt | [HP0x] Unknown | string |  
dial | [DP0x] Unknown |   |  

</body>
</html>

**Comment by naimo84** [comment]
Hi @gitmors ,

v0.5.0 is on the way 😉 Due to the fact I don't own these two models, it's a very theoretically implementation 😉 

Greets,
Benjamin

**Comment by gitmors** [comment]
Hallo Benjamin,

ich sehe du kommt auch aus aus Bayern.  Da könnte ich dir die Maschine ja fast vorbei fahren :). Super lieb dass du das hier bereitstellst. Wenn ich mit etwas behilflich sein kann, gib bitte bescheid, bin gerne bereit dazu, sollten noch Informationen abgehen. 

Grüße,
Moritz

**Comment by naimo84** [comment]
Hallo Moritz,

ja München-->Regensburg wäre gar nicht soo weit :) 

https://flows.nodered.org/node/node-red-contrib-dyson-purelink ist aktualisiert und meine NodeRED Instanzen melden auch, dass ein Update verfügbar ist. Wenn du also mal testen magst? 

Aktuell hab ich alle Infos, denke ich. Danke 👍 

Grüße,
Benjamin
