### ISSUE TITLE
Support for Pure Cool TP04

### ISSUE THREAD

**Issue by ninjakatze** [naimo84/node-red-contrib-dyson-purelink#4]
I installed the nodes and communication seems to work. getTemperature and setFanSpeed are working but I can’t neither turn the device on or off nor setting it to auto mode. Can you add support for tp04?

**Comment by ninjakatze** [comment]
Thanks for adding support for TP04, i've updated the module but get the following error:
Error: /home/pi/.node-red/node_modules/node-red-contrib-dyson-purelink/dist/dyson-config.html does not exist
Error: /home/pi/.node-red/node_modules/node-red-contrib-dyson-purelink/dist/dyson-link.html does not exist

Do you know what to do? I already de- and reinstalled the node

**Comment by naimo84** [comment]
Hi,
I'm sorry, it was my mistake... I gitignored the dist folder. This seems to lead to this error.
I fixed it and published a new version.

Greets,
Benjamin

**Comment by ninjakatze** [comment]
No worries, the newer version works fine. All nodes are functional now and I can finally switch my fan via node red. The only function which didn’t work for me is setFanSpeed. I do know that I have to provide an additional attribute but all I get is a response with the current fan level. My message looks as follows: msg.payload = {
”action”: ”setFanSpeed“, ”speed”: 1}

**Comment by naimo84** [comment]
Hi @ninjakatze, 

sorry for the big delay. Bussy working-days, time consuming baby and so on 😉 
Have you tried the percent in percent? so 100 instead of 1?

 msg.payload = {”action”: ”setFanSpeed“, ”speed”: 100}
 msg.payload = {”action”: ”setFanSpeed“, ”speed”: 50}
...

In your initial post you are writing, that it's working your you 😉 

Greetz,
Benjamin

**Comment by ninjakatze** [comment]
Hi Benjamin,
No worries, same here I‘m also drowning in work. Didn‘t know that I have to provide percentages but now it’s working. Apparently that’s what I did when I tested it first time. There is one little flaw though, I can‘t set it to 100%. I’ve seen that you divide the value by ten again and add leading zeros. Could it be that you end up with 00010 - a value the device can’t handle?
Regards

**Comment by naimo84** [comment]
Unfortunately I can't find any hint, why the device can't handle the 100% value at all... I'm sorry for that @ninjakatze 
😞
