### ISSUE TITLE
Cannot select a device

### ISSUE THREAD

**Issue by jncarter123** [naimo84/node-red-contrib-dyson-purelink#5]
Thank you for writing this plugin and I'm excited to use it. I am able to configure it and the device search shows a list of my 3 pure hot + cool link. However I cannot select from the list. I'm sorry I'm not more familiar with creating nodes to find the issue directly. Thank you!
<img width="498" alt="Node-RED___192_168_51_21" src="https://user-images.githubusercontent.com/30420708/74959278-e3003a00-53cf-11ea-8be3-080a18718760.png">

**Comment by naimo84** [comment]
Hey jncarter,

I'm sorry, I found this issue a week ago, but didn't publish a new version. 

So, should be fixed with v0.1.1 😉 Published a minute ago.

Greets,
Benjamin

**Comment by jncarter123** [comment]
Benjamin,
Thank you for pushing the update. I installed it and am now able to select a device. 

I was able to pull a temperature from one device, one time.  I'm looking into that now. I just dont get any sort of log, errror, anything back. 

I did notice that when I change the node to another device, I get the following error: "Error stopping node: TypeError: Cannot read property 'disconnect' of undefined".

**Comment by naimo84** [comment]
Jncarter,

unfortunatelly I only own one dyson purifier. So this will be hard for me to test. I published a new version. May you please try this one? 

Kind regards,
Benjamin

**Comment by jncarter123** [comment]
Benjamin,
I've updated and enabled debug logging. I can see the 3 devices in the log. However it appears that some of the data is missing?

`["ip":null,"url":null,"name":"Salon","port":null](url)`

I don't see anything logged when I inject the flow to perform an action on a device.

-jeremy

**Comment by jncarter123** [comment]
I checked and avahi is installed and running on the pi. I browsed but I don't see any devices with service type dyson_mqtt. So maybe it is an issue with discovering the devices...

-jeremy

**Comment by jncarter123** [comment]
It seems to be somewhat intermittent. It suddenly started working and I started seeing additional logs. 

`Feb 28 02:26:48 Got network device: AXX-XX-XXXXXXXX
Feb 28 02:26:48 28 Feb 02:26:48 - [debug] [dyson-link:1498129e.fff06d] Network_device: {"name":"455_AXX-XX-XXXXXXXX","ip":"192.168.XXX.XXX","port":1883,"serial":"AXX-XX-XXXXXXXX","mqttPrefix":"455"}
Feb 28 02:26:48 Got network device: AYY-YY-YYYYYYYY
Feb 28 02:26:48 28 Feb 02:26:48 - [debug] [dyson-link:1498129e.fff06d] Network_device: {"name":"455_AYY-YY-YYYYYYYY","ip":"192.168.XXX.XXX","port":1883,"serial":"AYY-YY-YYYYYYYY","mqttPrefix":"455"}
Feb 28 02:26:48 Got network device: SZZ-ZZ-ZZZZZZZ
Feb 28 02:26:48 28 Feb 02:26:48 - [debug] [dyson-link:1498129e.fff06d] Network_device: {"name":"455_AZZ-ZZ-ZZZZZZZZ","ip":"192.168.XXX.XXX","port":1883,"serial":"AZZ-ZZ-ZZZZZZZZ","mqttPrefix":"455"}
Feb 28 02:28:13 28 Feb 02:28:13 - [debug] [dyson-link:1498129e.fff06d] action: getTemperature`
